# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
import torch

# Create a random tensor with shape (7, 7)
random_tensor = torch.rand((7, 7))

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [3]:
# Perform matrix multiplication with another random tensor of shape (1, 7)
second_tensor = torch.rand((1, 7)).t()  # Transpose to match dimensions
result_matrix = torch.mm(random_tensor, second_tensor)

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [16]:
# Set random seed to 0
torch.manual_seed(0)

# Create two random tensors and perform matrix multiplication
torch.manual_seed(0)  # Ensure reproducibility
random_tensor_a = torch.rand((7, 7))
random_tensor_b = torch.rand((1, 7)).t()
result_seed_matrix = torch.mm(random_tensor_a, random_tensor_b)

# Print the result matrix and its shape
print("Result Seed Matrix:")
print(result_seed_matrix, result_seed_matrix.shape)


Result Seed Matrix:
tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]]) torch.Size([7, 1])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [5]:
# Set GPU random seed to 1234 if there is an equivalent
torch.cuda.manual_seed(1234) if torch.cuda.is_available() else None


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [15]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Create two random tensors on GPU
tensor_a_gpu = torch.rand((2, 3), device=device)
tensor_b_gpu = torch.rand((2, 3), device=device)

# Print tensors on GPU
print("Device:", device)
print("Tensor A on GPU:", tensor_a_gpu)
print("Tensor B on GPU:", tensor_b_gpu)

Device: cuda
Tensor A on GPU: tensor([[0.1272, 0.8167, 0.5440],
        [0.6601, 0.2721, 0.9737]], device='cuda:0')
Tensor B on GPU: tensor([[0.6208, 0.0276, 0.3255],
        [0.1114, 0.6812, 0.3608]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [14]:
# Perform matrix multiplication on tensors created on GPU
result_matrix_gpu = torch.mm(tensor_a_gpu, tensor_b_gpu.t())

# Print the result matrix and its shape
print("Result Matrix on GPU:", result_matrix_gpu, result_matrix_gpu.shape)

Result Matrix on GPU: tensor([[0.2786, 0.7668],
        [0.7343, 0.6102]], device='cuda:0') torch.Size([2, 2])


### 8. Find the maximum and minimum values of the output of 7.

In [8]:
# Find max and min values of the output
max_value = torch.max(result_matrix_gpu)
min_value = torch.min(result_matrix_gpu)

### 9. Find the maximum and minimum index values of the output of 7.

In [9]:
# Find indices of max and min values
argmax_index = torch.argmax(result_matrix_gpu)
argmin_index = torch.argmin(result_matrix_gpu)


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [13]:
# Set seed
torch.manual_seed(7)

# Create a random tensor with shape (1, 1, 1, 10)
initial_tensor = torch.rand((1, 1, 1, 10))

# Remove single dimensions
modified_tensor = initial_tensor.squeeze().view(10)

# Print the tensors and their shapes
print("Initial Tensor:", initial_tensor, initial_tensor.shape)
print("Modified Tensor:", modified_tensor, modified_tensor.shape)

Initial Tensor: tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
Modified Tensor: tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
